<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bank;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            ['sandi_bank' => '014', 'nama_bank' => 'Bank Central Asia (BCA)'],
            ['sandi_bank' => '008', 'nama_bank' => 'Bank Mandiri'],
            ['sandi_bank' => '009', 'nama_bank' => 'Bank Negara Indonesia (BNI)'],
            ['sandi_bank' => '002', 'nama_bank' => 'Bank Rakyat Indonesia (BRI)'],
            ['sandi_bank' => '011', 'nama_bank' => 'Bank Danamon'],
            ['sandi_bank' => '013', 'nama_bank' => 'Bank Permata'],
            ['sandi_bank' => '016', 'nama_bank' => 'Bank International Indonesia (BII)'],
            ['sandi_bank' => '019', 'nama_bank' => 'Bank Pan Indonesia'],
            ['sandi_bank' => '022', 'nama_bank' => 'Bank CIMB Niaga'],
            ['sandi_bank' => '023', 'nama_bank' => 'Bank UOB Indonesia'],
            ['sandi_bank' => '028', 'nama_bank' => 'Bank OCBC NISP'],
            ['sandi_bank' => '031', 'nama_bank' => 'Citibank'],
            ['sandi_bank' => '037', 'nama_bank' => 'Bank Artha Graha Internasional'],
            ['sandi_bank' => '039', 'nama_bank' => 'Bank Central Asia (BCA) Syariah'],
            ['sandi_bank' => '040', 'nama_bank' => 'Bank HSBC Indonesia'],
            ['sandi_bank' => '042', 'nama_bank' => 'Bank Syariah Mandiri'],
            ['sandi_bank' => '045', 'nama_bank' => 'Bank BNI Syariah'],
            ['sandi_bank' => '046', 'nama_bank' => 'Bank BRI Syariah'],
            ['sandi_bank' => '147', 'nama_bank' => 'Bank Muamalat Indonesia'],
            ['sandi_bank' => '153', 'nama_bank' => 'Bank Sinarmas'],
            ['sandi_bank' => '157', 'nama_bank' => 'Bank Mestika Dharma'],
            ['sandi_bank' => '159', 'nama_bank' => 'Bank Tabungan Negara (BTN)'],
            ['sandi_bank' => '161', 'nama_bank' => 'Bank Maspion Indonesia'],
            ['sandi_bank' => '162', 'nama_bank' => 'Bank Hana'],
            ['sandi_bank' => '164', 'nama_bank' => 'Bank ICBC Indonesia'],
            ['sandi_bank' => '166', 'nama_bank' => 'Bank QNB Indonesia'],
            ['sandi_bank' => '167', 'nama_bank' => 'Bank Mayapada'],
            ['sandi_bank' => '212', 'nama_bank' => 'Bank Woori Saudara Indonesia 1906'],
            ['sandi_bank' => '213', 'nama_bank' => 'Bank BTPN'],
            ['sandi_bank' => '405', 'nama_bank' => 'Bank Victoria International'],
            ['sandi_bank' => '422', 'nama_bank' => 'Bank BRI Agroniaga'],
            ['sandi_bank' => '425', 'nama_bank' => 'Bank Bukopin'],
            ['sandi_bank' => '426', 'nama_bank' => 'Bank Mega'],
            ['sandi_bank' => '427', 'nama_bank' => 'Bank BNI 46'],
            ['sandi_bank' => '441', 'nama_bank' => 'Bank Bumi Arta'],
            ['sandi_bank' => '451', 'nama_bank' => 'Bank HSBC Indonesia'],
            ['sandi_bank' => '484', 'nama_bank' => 'Bank KEB Indonesia'],
            ['sandi_bank' => '485', 'nama_bank' => 'Bank BNP Paribas Indonesia'],
            ['sandi_bank' => '490', 'nama_bank' => 'Bank OCBC NISP'],
            ['sandi_bank' => '494', 'nama_bank' => 'Bank Rabobank International Indonesia'],
            ['sandi_bank' => '506', 'nama_bank' => 'Bank ANZ Indonesia'],
            ['sandi_bank' => '513', 'nama_bank' => 'Bank Permata'],
            ['sandi_bank' => '517', 'nama_bank' => 'Bank UOB Indonesia'],
            ['sandi_bank' => '520', 'nama_bank' => 'Bank JTrust Indonesia'],
            ['sandi_bank' => '521', 'nama_bank' => 'Bank MNC Internasional'],
            ['sandi_bank' => '523', 'nama_bank' => 'Bank SBI Indonesia'],
            ['sandi_bank' => '526', 'nama_bank' => 'Bank Ganesha'],
            ['sandi_bank' => '531', 'nama_bank' => 'Bank INA Perdana'],
            ['sandi_bank' => '535', 'nama_bank' => 'Bank Sahabat Sampoerna'],
            ['sandi_bank' => '536', 'nama_bank' => 'Bank BCA Syariah'],
            ['sandi_bank' => '542', 'nama_bank' => 'Bank BRI Syariah'],
            ['sandi_bank' => '547', 'nama_bank' => 'Bank BTPN Syariah'],
            ['sandi_bank' => '553', 'nama_bank' => 'Bank Mayora'],
            ['sandi_bank' => '555', 'nama_bank' => 'Bank Index Selindo'],
            ['sandi_bank' => '559', 'nama_bank' => 'Bank Central Asia (BCA)'],
            ['sandi_bank' => '562', 'nama_bank' => 'Bank Fama Internasional'],
            ['sandi_bank' => '564', 'nama_bank' => 'Bank Mandiri Syariah'],
            ['sandi_bank' => '566', 'nama_bank' => 'Bank Multi Arta Sentosa'],
            ['sandi_bank' => '567', 'nama_bank' => 'Bank Harda Internasional'],
            ['sandi_bank' => '945', 'nama_bank' => 'Bank China Construction Bank Indonesia'],
            ['sandi_bank' => '947', 'nama_bank' => 'Bank DBS Indonesia'],
            ['sandi_bank' => '948', 'nama_bank' => 'Bank Resona Perdania'],
            ['sandi_bank' => '949', 'nama_bank' => 'Bank Mizuho Indonesia'],
            ['sandi_bank' => '950', 'nama_bank' => 'Bank Commonwealth'],
            ['sandi_bank' => '951', 'nama_bank' => 'Bank Chinatrust Indonesia'],
            ['sandi_bank' => '952', 'nama_bank' => 'Bank Sumitomo Mitsui Indonesia'],
            ['sandi_bank' => '953', 'nama_bank' => 'Bank Windu Kentjana International'],
            ['sandi_bank' => '954', 'nama_bank' => 'Bank Capital Indonesia'],
            ['sandi_bank' => '955', 'nama_bank' => 'Bank BNP Paribas Indonesia'],
            ['sandi_bank' => '956', 'nama_bank' => 'Bank UOB Indonesia'],
            ['sandi_bank' => '957', 'nama_bank' => 'Bank Deutsche Bank Indonesia'],
            ['sandi_bank' => '958', 'nama_bank' => 'Bank Woori Saudara Indonesia 1906'],
            ['sandi_bank' => '959', 'nama_bank' => 'Bank BCA Syariah'],
            ['sandi_bank' => '960', 'nama_bank' => 'Bank Muamalat Indonesia'],
            ['sandi_bank' => '961', 'nama_bank' => 'Bank MNC Internasional'],
            ['sandi_bank' => '962', 'nama_bank' => 'Bank BTPN'],
            ['sandi_bank' => '963', 'nama_bank' => 'Bank CIMB Niaga'],
            ['sandi_bank' => '964', 'nama_bank' => 'Bank OCBC NISP'],
            ['sandi_bank' => '965', 'nama_bank' => 'Bank Permata'],
            ['sandi_bank' => '966', 'nama_bank' => 'Bank Danamon'],
            ['sandi_bank' => '967', 'nama_bank' => 'Bank Pan Indonesia'],
            ['sandi_bank' => '968', 'nama_bank' => 'Bank Artha Graha Internasional'],
            ['sandi_bank' => '969', 'nama_bank' => 'Bank Victoria International'],
            ['sandi_bank' => '970', 'nama_bank' => 'Bank Bukopin'],
            ['sandi_bank' => '971', 'nama_bank' => 'Bank Mega'],
            ['sandi_bank' => '972', 'nama_bank' => 'Bank Sinarmas'],
            ['sandi_bank' => '973', 'nama_bank' => 'Bank Mestika Dharma'],
            ['sandi_bank' => '974', 'nama_bank' => 'Bank Tabungan Negara (BTN)'],
            ['sandi_bank' => '975', 'nama_bank' => 'Bank Maspion Indonesia'],
            ['sandi_bank' => '976', 'nama_bank' => 'Bank Hana'],
            ['sandi_bank' => '977', 'nama_bank' => 'Bank ICBC Indonesia'],
            ['sandi_bank' => '978', 'nama_bank' => 'Bank QNB Indonesia'],
            ['sandi_bank' => '979', 'nama_bank' => 'Bank Mayapada'],
            ['sandi_bank' => '980', 'nama_bank' => 'Bank Woori Saudara Indonesia 1906'],
            ['sandi_bank' => '981', 'nama_bank' => 'Bank BTPN'],
            ['sandi_bank' => '982', 'nama_bank' => 'Bank Victoria International'],
            ['sandi_bank' => '983', 'nama_bank' => 'Bank BRI Agroniaga'],
            ['sandi_bank' => '984', 'nama_bank' => 'Bank Bukopin'],
            ['sandi_bank' => '985', 'nama_bank' => 'Bank Mega'],
            ['sandi_bank' => '986', 'nama_bank' => 'Bank BNI 46'],
            ['sandi_bank' => '987', 'nama_bank' => 'Bank Bumi Arta'],
            ['sandi_bank' => '988', 'nama_bank' => 'Bank HSBC Indonesia'],
            ['sandi_bank' => '989', 'nama_bank' => 'Bank KEB Indonesia'],
            ['sandi_bank' => '990', 'nama_bank' => 'Bank BNP Paribas Indonesia'],
            ['sandi_bank' => '991', 'nama_bank' => 'Bank OCBC NISP'],
            ['sandi_bank' => '992', 'nama_bank' => 'Bank Rabobank International Indonesia'],
            ['sandi_bank' => '993', 'nama_bank' => 'Bank ANZ Indonesia'],
            ['sandi_bank' => '994', 'nama_bank' => 'Bank Permata'],
            ['sandi_bank' => '995', 'nama_bank' => 'Bank UOB Indonesia'],
            ['sandi_bank' => '996', 'nama_bank' => 'Bank JTrust Indonesia'],
            ['sandi_bank' => '997', 'nama_bank' => 'Bank MNC Internasional'],
            ['sandi_bank' => '998', 'nama_bank' => 'Bank SBI Indonesia'],
            ['sandi_bank' => '999', 'nama_bank' => 'Bank Ganesha'],
        ];

        foreach ($banks as $bank) {
            Bank::firstOrCreate(
                ['sandi_bank' => $bank['sandi_bank']],
                $bank
            );
        }
    }
} 